#!/bin/bash

# Run test first
./script/test

build_dir="build"
app_dir="app"
entry_point="index.js"
target_point="movie_map"

# Delete app/build dir
rm -rf $app_dir/$build_dir

# Create a build folder
mkdir $app_dir/$build_dir/

cp src/css/movie_map.css $build_dir/movie_map.css
rollup -c -f umd -n movie_map -o $build_dir/$target_point.js -- $entry_point

# Remember live reload happens only with app build, once done prepublish has to be run again
cp src/css/movie_map.css $app_dir/$build_dir/movie_map.css
rollup -c $1 -f umd -n movie_map -o $app_dir/$build_dir/$target_point.js -- $entry_point

# uglify seems to not work so well with es6 code
# uglifyjs $build_dir/$target_point.js -c negate_iife=false -m -o $build_dir/$target_point.min.js
