#!/bin/bash

# Set the error flog so that it stops at the first error
set -e

build_dir="build"

# Delete pre existing folder, if any
rm -rf $build_dir

# Create build folder
mkdir $build_dir

json2module package.json > build/package.js

node rollup.node
